server:
  port: 8081  #tomcat 启动端口号

#服务注册中心配置
eureka:

  client:
    serviceUrl:
      #这个地址填的是注册中心eureka-server的地址
      defaultZone: http://localhost:8080/eureka/
    healthcheck:
      enabled: true
spring :
     application:
       name: provider
     datasource:
       username: root
       password: yuzhe19940615
       url: jdbc:mysql://122.51.207.132:3306/mysql?useUnicode=true&characterEncoding=UTF-8
       driver-class-name: com.mysql.jdbc.Driver
       hikari:
         connection-timeout: 6000
         maximum-pool-size: 5
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
